#include "engine.hpp"
#include <algorithm>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
namespace { std::string escape(const std::string& value){std::string out;for(char c:value){if(c=='\\')out+="\\\\";else if(c=='\"')out+="\\\"";else out+=c;}return out;} std::string field(const std::string& body,const std::string& name,const std::string& fallback){auto p=body.find("\""+name+"\"");if(p==std::string::npos)return fallback;p=body.find(':',p);if(p==std::string::npos)return fallback;++p;while(p<body.size()&&(body[p]==' '||body[p]=='\t'))++p;if(p<body.size()&&body[p]=='\"'){++p;auto e=body.find('"',p);return e==std::string::npos?body.substr(p):body.substr(p,e-p);}auto e=body.find_first_of(",}",p);return body.substr(p,e==std::string::npos?body.size()-p:e-p);} uint64_t setting(const std::string& path,const std::string& key,uint64_t fallback){std::ifstream file(path+"/storage.env");std::string line;while(std::getline(file,line))if(line.rfind(key+"=",0)==0)try{return std::stoull(line.substr(key.size()+1));}catch(...){break;}return fallback;} }
Engine::Engine(std::string dataDirectory):directory(std::move(dataDirectory)),memtable(8),walFile(directory+"/wal.log"),tables(directory){std::filesystem::create_directories(directory);sequence=tables.maxGeneration();recover();}
size_t Engine::memtableLimitBytes()const{return setting(directory,"MEMTABLE_SIZE_MB",1)*1024*1024;}
void Engine::recover(){try{for(const auto& entry:walFile.replay()){sequence=std::max(sequence,entry.sequence);memtable.put(entry.key,{entry.value,entry.operation=="DEL",entry.sequence});}}catch(const std::runtime_error&){std::error_code error;std::filesystem::rename(directory+"/wal.log",directory+"/wal.log.legacy",error);if(error)throw;}}
void Engine::put(const std::string& key,const std::string& value){std::lock_guard lock(mutex);walFile.append("PUT",key,value,++sequence);memtable.put(key,{value,false,sequence});logicalBytes+=key.size()+value.size();if(memtable.bytes()>=memtableLimitBytes())flush();}
void Engine::del(const std::string& key){std::lock_guard lock(mutex);walFile.append("DEL",key,"",++sequence);memtable.put(key,{"",true,sequence});logicalBytes+=key.size();if(memtable.bytes()>=memtableLimitBytes())flush();}
bool Engine::get(const std::string& key,std::string& value){std::lock_guard lock(mutex);++readOperations;Record record;if(memtable.get(key,record)){if(record.tombstone){++readMisses;return false;}value=record.value;return true;}if(tables.get(key,value,bloomRejects,diskReads))return true;++readMisses;return false;}
void Engine::flush(){std::lock_guard lock(mutex);if(!memtable.size())return;auto records=memtable.snapshot();tables.write(records);for(const auto& [key,record]:records)internalBytes+=key.size()+record.value.size()+sizeof(Record);memtable.clear();walFile.truncate();++flushCount;}
size_t Engine::compact(){std::lock_guard lock(mutex);if(memtable.size())tables.write(memtable.snapshot(),"L0");memtable.clear();auto removed=tables.compact();walFile.truncate();return removed;}
void Engine::crashRecover(){std::lock_guard lock(mutex);memtable.clear();recover();}
std::string Engine::status()const{std::lock_guard lock(mutex);size_t tombstones=0;for(auto& item:memtable.snapshot())if(item.second.tombstone)++tombstones;auto metadata=tables.metadata();double hit=readOperations?double(readOperations-readMisses)/readOperations:0;std::ostringstream out;out<<"{\"memtableKeys\":"<<memtable.size()<<",\"memtableBytes\":"<<memtable.bytes()<<",\"tombstones\":"<<tombstones<<",\"sstables\":"<<metadata.size()<<",\"walBytes\":"<<walFile.bytes()<<",\"walRecords\":"<<walFile.records()<<",\"readOps\":"<<readOperations<<",\"readMisses\":"<<readMisses<<",\"readHitRate\":"<<hit<<",\"memtableType\":\"skip list\",\"skiplistLevels\":"<<memtable.levels()<<",\"memtablePreview\":[";size_t n=0;for(auto& [key,record]:memtable.snapshot(40)){if(n++)out<<',';out<<"{\"key\":\""<<escape(key)<<"\",\"state\":\""<<(record.tombstone?"TOMBSTONE":"VALUE")<<"\",\"bytes\":"<<key.size()+record.value.size()<<"}";}out<<"],\"sstableFiles\":[";for(size_t i=0;i<metadata.size();++i){if(i)out<<',';out<<"{\"name\":\""<<escape(metadata[i].name)<<"\",\"level\":\""<<metadata[i].level<<"\",\"records\":"<<metadata[i].records<<",\"bytes\":"<<metadata[i].bytes<<"}";}out<<"]}";return out.str();}
std::string Engine::metrics()const{std::lock_guard lock(mutex);std::ostringstream out;out<<"{\"memtableType\":\"skip list\",\"skiplistLevels\":"<<memtable.levels()<<",\"memtableBytes\":"<<memtable.bytes()<<",\"sstableReadOps\":"<<diskReads<<",\"bloomRejects\":"<<bloomRejects<<",\"cacheHits\":"<<cacheHits<<",\"pendingRequests\":"<<pendingRequests.load()<<",\"activeRequests\":"<<activeRequests.load()<<"}";return out.str();}
std::string Engine::wal()const{std::lock_guard lock(mutex);std::ostringstream out;out<<"[";auto entries=walFile.replay();for(size_t i=0;i<entries.size();++i){if(i)out<<',';out<<"{\"seq\":"<<entries[i].sequence<<",\"operation\":\""<<entries[i].operation<<"\",\"key\":\""<<escape(entries[i].key)<<"\",\"valueBytes\":"<<entries[i].value.size()<<"}";}out<<"]";return out.str();}
std::string Engine::sstables()const{std::lock_guard lock(mutex);std::ostringstream out;out<<"[";auto metadata=tables.metadata();for(size_t i=0;i<metadata.size();++i){if(i)out<<',';auto&m=metadata[i];out<<"{\"name\":\""<<escape(m.name)<<"\",\"level\":\""<<m.level<<"\",\"records\":"<<m.records<<",\"bytes\":"<<m.bytes<<",\"indexBytes\":"<<m.indexEntries*16<<",\"bloom\":\"healthy\",\"minKey\":\""<<escape(m.minKey)<<"\",\"maxKey\":\""<<escape(m.maxKey)<<"\"}";}out<<"]";return out.str();}
std::string Engine::config()const{std::ostringstream out;out<<"{\"storage\":\"local files\",\"MEMTABLE_SIZE_MB\":"<<setting(directory,"MEMTABLE_SIZE_MB",1)<<",\"COMPACTION_POLICY\":\"leveled\"}";return out.str();}
void Engine::saveConfig(const std::string& body){std::ofstream file(directory+"/storage.env",std::ios::trunc);file<<"MEMTABLE_SIZE_MB="<<field(body,"MEMTABLE_SIZE_MB","1")<<'\n'<<"COMPACTION_POLICY="<<field(body,"COMPACTION_POLICY","leveled")<<'\n';}
