#include "sstable.hpp"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <functional>
#include <map>
#include <stdexcept>
namespace {
constexpr uint64_t Magic = 0x3154534D534CULL;
struct Header { uint64_t magic, generation, records, bloomBits, indexEntries; uint32_t level; };
uint32_t levelNumber(const std::string& level) { return level.size() > 1 && level[0] == 'L' ? std::stoul(level.substr(1)) : 0; }
void writeBytes(std::ofstream& file, const void* data, size_t size) { file.write(static_cast<const char*>(data), static_cast<std::streamsize>(size)); if (!file) throw std::runtime_error("SSTable write failed"); }
void readBytes(std::ifstream& file, void* data, size_t size) { file.read(static_cast<char*>(data), static_cast<std::streamsize>(size)); if (!file) throw std::runtime_error("truncated SSTable"); }
}
SSTableStore::SSTableStore(std::string dir, size_t bloomBitCount) : directory(std::move(dir)), bits(std::max<size_t>(1024, bloomBitCount)) { std::filesystem::create_directories(directory); std::vector<std::tuple<uint64_t,std::string,std::string>> files; std::ifstream manifest(directory+"/MANIFEST"); uint64_t generation; uint32_t level; std::string name; while(manifest>>generation>>level>>name) files.emplace_back(generation,"L"+std::to_string(level),name); if(files.empty()) for(const auto& entry:std::filesystem::directory_iterator(directory)) if(entry.path().extension()==".sst") files.emplace_back(0,"L0",entry.path().filename().string()); std::sort(files.begin(),files.end()); for(const auto& [stored,levelName,fileName]:files) if(std::filesystem::exists(directory+"/"+fileName)){try{inspect(fileName,levelName);tableList.back().generation=stored;}catch(const std::exception&){std::error_code error;std::filesystem::rename(directory+"/"+fileName,directory+"/"+fileName+".legacy",error);if(error)throw;}} }
size_t SSTableStore::hash(const std::string& key,size_t seed)const{return std::hash<std::string>{}(key+":"+std::to_string(seed))%bits;}
void SSTableStore::inspect(const std::string& name,const std::string& level){TableMeta meta;meta.name=name;meta.level=level;std::ifstream file(directory+"/"+name,std::ios::binary);Header header{};readBytes(file,&header,sizeof(header));if(header.magic!=Magic||header.records>100000000||header.indexEntries>header.records+1||header.bloomBits<1024||header.bloomBits>(1ULL<<30))throw std::runtime_error("corrupt SSTable header");meta.generation=header.generation;meta.records=static_cast<size_t>(header.records);meta.indexEntries=static_cast<size_t>(header.indexEntries);meta.bloomBits=static_cast<size_t>(header.bloomBits);meta.bloom.assign((meta.bloomBits+63)/64,0);for(uint64_t i=0;i<header.indexEntries;++i){uint32_t keySize;uint64_t offset;readBytes(file,&keySize,4);readBytes(file,&offset,8);if(keySize>16*1024*1024)throw std::runtime_error("corrupt SSTable index");std::string key(keySize,'\0');readBytes(file,key.data(),keySize);meta.index.emplace_back(std::move(key),offset);}for(uint64_t i=0;i<header.records;++i){uint32_t keySize,valueSize;uint64_t sequence;uint8_t tombstone;readBytes(file,&keySize,4);readBytes(file,&valueSize,4);readBytes(file,&sequence,8);readBytes(file,&tombstone,1);if(keySize>16*1024*1024||valueSize>256*1024*1024||tombstone>1)throw std::runtime_error("corrupt SSTable record");std::string key(keySize,'\0'),value(valueSize,'\0');readBytes(file,key.data(),keySize);readBytes(file,value.data(),valueSize);if(i==0)meta.minKey=key;meta.maxKey=key;for(size_t seed=0;seed<3;++seed){auto bit=hash(key,seed);meta.bloom[bit/64]|=1ULL<<(bit%64);}}std::error_code error;meta.bytes=std::filesystem::file_size(directory+"/"+name,error);if(error)throw std::runtime_error("cannot stat SSTable");tableList.push_back(std::move(meta));}
std::string SSTableStore::write(const std::vector<std::pair<std::string,Record>>& records,const std::string& level,uint64_t generation){if(!generation)generation=maxGeneration()+1;std::string name="table-"+std::to_string(generation)+".sst",temp=directory+"/."+name+".tmp",path=directory+"/"+name;uint64_t indexCount=(records.size()+15)/16,dataStart=sizeof(Header);for(size_t i=0;i<records.size();++i)if(i%16==0)dataStart+=12+records[i].first.size();Header header{Magic,generation,records.size(),bits,indexCount,levelNumber(level)};std::ofstream file(temp,std::ios::binary|std::ios::trunc);if(!file)throw std::runtime_error("cannot create SSTable");writeBytes(file,&header,sizeof(header));uint64_t recordOffset=dataStart;for(size_t i=0;i<records.size();++i)if(i%16==0){uint32_t keySize=records[i].first.size();writeBytes(file,&keySize,4);writeBytes(file,&recordOffset,8);writeBytes(file,records[i].first.data(),keySize);recordOffset+=17+keySize+records[i].second.value.size();}for(const auto& [key,record]:records){uint32_t keySize=key.size(),valueSize=record.value.size();uint8_t tombstone=record.tombstone;writeBytes(file,&keySize,4);writeBytes(file,&valueSize,4);writeBytes(file,&record.sequence,8);writeBytes(file,&tombstone,1);writeBytes(file,key.data(),keySize);writeBytes(file,record.value.data(),valueSize);}file.flush();if(!file)throw std::runtime_error("SSTable flush failed");file.close();std::error_code error;std::filesystem::rename(temp,path,error);if(error){std::filesystem::remove(temp);throw std::runtime_error("SSTable publish failed");}std::filesystem::create_directories(directory+"/object-store");std::filesystem::copy_file(path,directory+"/object-store/"+name,std::filesystem::copy_options::overwrite_existing,error);if(error)throw std::runtime_error("object-store mirror failed");inspect(name,level);tableList.back().generation=generation;std::ofstream manifest(directory+"/.MANIFEST.tmp",std::ios::trunc);for(const auto& table:tableList)manifest<<table.generation<<' '<<levelNumber(table.level)<<' '<<table.name<<'\n';manifest.flush();if(!manifest)throw std::runtime_error("manifest write failed");manifest.close();std::filesystem::rename(directory+"/.MANIFEST.tmp",directory+"/MANIFEST",error);if(error)throw std::runtime_error("manifest publish failed");return name;}
bool SSTableStore::get(const std::string& key,std::string& value,size_t& rejects,size_t& reads){for(auto table=tableList.rbegin();table!=tableList.rend();++table){if((!table->minKey.empty()&&key<table->minKey)||(!table->maxKey.empty()&&key>table->maxKey)){++rejects;continue;}bool present=true;for(size_t seed=0;seed<3;++seed){auto bit=hash(key,seed);if(!(table->bloom[bit/64]&(1ULL<<(bit%64)))){present=false;break;}}if(!present){++rejects;continue;}uint64_t offset=sizeof(Header);for(const auto& [indexKey,indexOffset]:table->index){if(indexKey>key)break;offset=indexOffset;}std::ifstream file(directory+"/"+table->name,std::ios::binary);file.seekg(static_cast<std::streamoff>(offset));for(size_t i=0;i<16;++i){uint32_t keySize,valueSize;uint64_t sequence;uint8_t tombstone;if(!file.read(reinterpret_cast<char*>(&keySize),4)||!file.read(reinterpret_cast<char*>(&valueSize),4)||!file.read(reinterpret_cast<char*>(&sequence),8)||!file.read(reinterpret_cast<char*>(&tombstone),1))break;if(keySize>16*1024*1024||valueSize>256*1024*1024)throw std::runtime_error("corrupt SSTable record");std::string stored(keySize,'\0'),storedValue(valueSize,'\0');readBytes(file,stored.data(),keySize);readBytes(file,storedValue.data(),valueSize);if(stored==key){++reads;if(tombstone)return false;value=std::move(storedValue);return true;}if(stored>key)break;}}return false;}
size_t SSTableStore::compact(){std::map<std::string,Record> merged;for(const auto& table:tableList){std::ifstream file(directory+"/"+table.name,std::ios::binary);Header header{};readBytes(file,&header,sizeof(header));for(uint64_t i=0;i<header.indexEntries;++i){uint32_t keySize;uint64_t offset;readBytes(file,&keySize,4);readBytes(file,&offset,8);file.seekg(keySize,std::ios::cur);}for(uint64_t i=0;i<header.records;++i){uint32_t keySize,valueSize;uint64_t sequence;uint8_t tombstone;readBytes(file,&keySize,4);readBytes(file,&valueSize,4);readBytes(file,&sequence,8);readBytes(file,&tombstone,1);if(keySize>16*1024*1024||valueSize>256*1024*1024)throw std::runtime_error("corrupt SSTable record");std::string key(keySize,'\0'),value(valueSize,'\0');readBytes(file,key.data(),keySize);readBytes(file,value.data(),valueSize);Record record{std::move(value),tombstone!=0,sequence};auto current=merged.find(key);if(current==merged.end()||current->second.sequence<record.sequence)merged[key]=std::move(record);}}size_t removed=0;std::vector<std::pair<std::string,Record>> live;for(const auto& [key,record]:merged)if(record.tombstone)++removed;else live.emplace_back(key,record);auto oldTables=tableList;if(!live.empty())write(live,"L1");else{tableList.clear();std::ofstream manifest(directory+"/.MANIFEST.tmp",std::ios::trunc);manifest.close();std::error_code error;std::filesystem::rename(directory+"/.MANIFEST.tmp",directory+"/MANIFEST",error);if(error)throw std::runtime_error("manifest publish failed");}for(const auto& table:oldTables)if(std::none_of(tableList.begin(),tableList.end(),[&](const TableMeta& current){return current.name==table.name;})){std::error_code error;std::filesystem::remove(directory+"/"+table.name,error);if(error)throw std::runtime_error("SSTable delete failed");}return removed;}
uint64_t SSTableStore::maxGeneration()const{uint64_t value=0;for(const auto& table:tableList)value=std::max(value,table.generation);return value;}
